package cn.junang.sys.model;

public class Byuer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column byuer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column byuer.job_num
     *
     * @mbg.generated
     */
    private String jobNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column byuer.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column byuer.dept
     *
     * @mbg.generated
     */
    private Integer dept;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column byuer.id
     *
     * @return the value of byuer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column byuer.id
     *
     * @param id the value for byuer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column byuer.job_num
     *
     * @return the value of byuer.job_num
     *
     * @mbg.generated
     */
    public String getJobNum() {
        return jobNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column byuer.job_num
     *
     * @param jobNum the value for byuer.job_num
     *
     * @mbg.generated
     */
    public void setJobNum(String jobNum) {
        this.jobNum = jobNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column byuer.name
     *
     * @return the value of byuer.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column byuer.name
     *
     * @param name the value for byuer.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column byuer.dept
     *
     * @return the value of byuer.dept
     *
     * @mbg.generated
     */
    public Integer getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column byuer.dept
     *
     * @param dept the value for byuer.dept
     *
     * @mbg.generated
     */
    public void setDept(Integer dept) {
        this.dept = dept;
    }
}