package cn.junang.sys.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Chec_report {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chec_report.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chec_report.rep_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date repTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chec_report.productname
     *
     * @mbg.generated
     */
    private String productname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chec_report.ggmodel
     *
     * @mbg.generated
     */
    private String ggmodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chec_report.rep_username
     *
     * @mbg.generated
     */
    private String repUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chec_report.redescription
     *
     * @mbg.generated
     */
    private String redescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chec_report.rep_num
     *
     * @mbg.generated
     */
    private String repNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chec_report.id
     *
     * @return the value of chec_report.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chec_report.id
     *
     * @param id the value for chec_report.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chec_report.rep_time
     *
     * @return the value of chec_report.rep_time
     *
     * @mbg.generated
     */
    public Date getRepTime() {
        return repTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chec_report.rep_time
     *
     * @param repTime the value for chec_report.rep_time
     *
     * @mbg.generated
     */
    public void setRepTime(Date repTime) {
        this.repTime = repTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chec_report.productname
     *
     * @return the value of chec_report.productname
     *
     * @mbg.generated
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chec_report.productname
     *
     * @param productname the value for chec_report.productname
     *
     * @mbg.generated
     */
    public void setProductname(String productname) {
        this.productname = productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chec_report.ggmodel
     *
     * @return the value of chec_report.ggmodel
     *
     * @mbg.generated
     */
    public String getGgmodel() {
        return ggmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chec_report.ggmodel
     *
     * @param ggmodel the value for chec_report.ggmodel
     *
     * @mbg.generated
     */
    public void setGgmodel(String ggmodel) {
        this.ggmodel = ggmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chec_report.rep_username
     *
     * @return the value of chec_report.rep_username
     *
     * @mbg.generated
     */
    public String getRepUsername() {
        return repUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chec_report.rep_username
     *
     * @param repUsername the value for chec_report.rep_username
     *
     * @mbg.generated
     */
    public void setRepUsername(String repUsername) {
        this.repUsername = repUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chec_report.redescription
     *
     * @return the value of chec_report.redescription
     *
     * @mbg.generated
     */
    public String getRedescription() {
        return redescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chec_report.redescription
     *
     * @param redescription the value for chec_report.redescription
     *
     * @mbg.generated
     */
    public void setRedescription(String redescription) {
        this.redescription = redescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chec_report.rep_num
     *
     * @return the value of chec_report.rep_num
     *
     * @mbg.generated
     */
    public String getRepNum() {
        return repNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chec_report.rep_num
     *
     * @param repNum the value for chec_report.rep_num
     *
     * @mbg.generated
     */
    public void setRepNum(String repNum) {
        this.repNum = repNum;
    }
}