package cn.junang.sys.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Chec_plan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chec_plan.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chec_plan.pl_ltime
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date plLtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chec_plan.pl_username
     *
     * @mbg.generated
     */
    private String plUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chec_plan.pl_mains
     *
     * @mbg.generated
     */
    private String plMains;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chec_plan.pl_remarks
     *
     * @mbg.generated
     */
    private String plRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chec_plan.id
     *
     * @return the value of chec_plan.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chec_plan.id
     *
     * @param id the value for chec_plan.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chec_plan.pl_ltime
     *
     * @return the value of chec_plan.pl_ltime
     *
     * @mbg.generated
     */
    public Date getPlLtime() {
        return plLtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chec_plan.pl_ltime
     *
     * @param plLtime the value for chec_plan.pl_ltime
     *
     * @mbg.generated
     */
    public void setPlLtime(Date plLtime) {
        this.plLtime = plLtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chec_plan.pl_username
     *
     * @return the value of chec_plan.pl_username
     *
     * @mbg.generated
     */
    public String getPlUsername() {
        return plUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chec_plan.pl_username
     *
     * @param plUsername the value for chec_plan.pl_username
     *
     * @mbg.generated
     */
    public void setPlUsername(String plUsername) {
        this.plUsername = plUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chec_plan.pl_mains
     *
     * @return the value of chec_plan.pl_mains
     *
     * @mbg.generated
     */
    public String getPlMains() {
        return plMains;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chec_plan.pl_mains
     *
     * @param plMains the value for chec_plan.pl_mains
     *
     * @mbg.generated
     */
    public void setPlMains(String plMains) {
        this.plMains = plMains;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chec_plan.pl_remarks
     *
     * @return the value of chec_plan.pl_remarks
     *
     * @mbg.generated
     */
    public String getPlRemarks() {
        return plRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chec_plan.pl_remarks
     *
     * @param plRemarks the value for chec_plan.pl_remarks
     *
     * @mbg.generated
     */
    public void setPlRemarks(String plRemarks) {
        this.plRemarks = plRemarks;
    }
}