package cn.junang.sys.model;

import java.util.Date;

public class Chec_manage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chec_manage.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chec_manage.productname
     *
     * @mbg.generated
     */
    private String productname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chec_manage.ggmodel
     *
     * @mbg.generated
     */
    private String ggmodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chec_manage.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chec_manage.ma_number
     *
     * @mbg.generated
     */
    private Integer maNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chec_manage.ma_time
     *
     * @mbg.generated
     */
    private Date maTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chec_manage.ma_reason
     *
     * @mbg.generated
     */
    private String maReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chec_manage.ma_grade
     *
     * @mbg.generated
     */
    private Integer maGrade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chec_manage.id
     *
     * @return the value of chec_manage.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chec_manage.id
     *
     * @param id the value for chec_manage.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chec_manage.productname
     *
     * @return the value of chec_manage.productname
     *
     * @mbg.generated
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chec_manage.productname
     *
     * @param productname the value for chec_manage.productname
     *
     * @mbg.generated
     */
    public void setProductname(String productname) {
        this.productname = productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chec_manage.ggmodel
     *
     * @return the value of chec_manage.ggmodel
     *
     * @mbg.generated
     */
    public String getGgmodel() {
        return ggmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chec_manage.ggmodel
     *
     * @param ggmodel the value for chec_manage.ggmodel
     *
     * @mbg.generated
     */
    public void setGgmodel(String ggmodel) {
        this.ggmodel = ggmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chec_manage.unit
     *
     * @return the value of chec_manage.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chec_manage.unit
     *
     * @param unit the value for chec_manage.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chec_manage.ma_number
     *
     * @return the value of chec_manage.ma_number
     *
     * @mbg.generated
     */
    public Integer getMaNumber() {
        return maNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chec_manage.ma_number
     *
     * @param maNumber the value for chec_manage.ma_number
     *
     * @mbg.generated
     */
    public void setMaNumber(Integer maNumber) {
        this.maNumber = maNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chec_manage.ma_time
     *
     * @return the value of chec_manage.ma_time
     *
     * @mbg.generated
     */
    public Date getMaTime() {
        return maTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chec_manage.ma_time
     *
     * @param maTime the value for chec_manage.ma_time
     *
     * @mbg.generated
     */
    public void setMaTime(Date maTime) {
        this.maTime = maTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chec_manage.ma_reason
     *
     * @return the value of chec_manage.ma_reason
     *
     * @mbg.generated
     */
    public String getMaReason() {
        return maReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chec_manage.ma_reason
     *
     * @param maReason the value for chec_manage.ma_reason
     *
     * @mbg.generated
     */
    public void setMaReason(String maReason) {
        this.maReason = maReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chec_manage.ma_grade
     *
     * @return the value of chec_manage.ma_grade
     *
     * @mbg.generated
     */
    public Integer getMaGrade() {
        return maGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chec_manage.ma_grade
     *
     * @param maGrade the value for chec_manage.ma_grade
     *
     * @mbg.generated
     */
    public void setMaGrade(Integer maGrade) {
        this.maGrade = maGrade;
    }
}