package cn.junang.sys.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class Chec_reportExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    public Chec_reportExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRepTimeIsNull() {
            addCriterion("rep_time is null");
            return (Criteria) this;
        }

        public Criteria andRepTimeIsNotNull() {
            addCriterion("rep_time is not null");
            return (Criteria) this;
        }

        public Criteria andRepTimeEqualTo(Date value) {
            addCriterionForJDBCDate("rep_time =", value, "repTime");
            return (Criteria) this;
        }

        public Criteria andRepTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("rep_time <>", value, "repTime");
            return (Criteria) this;
        }

        public Criteria andRepTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("rep_time >", value, "repTime");
            return (Criteria) this;
        }

        public Criteria andRepTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("rep_time >=", value, "repTime");
            return (Criteria) this;
        }

        public Criteria andRepTimeLessThan(Date value) {
            addCriterionForJDBCDate("rep_time <", value, "repTime");
            return (Criteria) this;
        }

        public Criteria andRepTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("rep_time <=", value, "repTime");
            return (Criteria) this;
        }

        public Criteria andRepTimeIn(List<Date> values) {
            addCriterionForJDBCDate("rep_time in", values, "repTime");
            return (Criteria) this;
        }

        public Criteria andRepTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("rep_time not in", values, "repTime");
            return (Criteria) this;
        }

        public Criteria andRepTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("rep_time between", value1, value2, "repTime");
            return (Criteria) this;
        }

        public Criteria andRepTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("rep_time not between", value1, value2, "repTime");
            return (Criteria) this;
        }

        public Criteria andProductnameIsNull() {
            addCriterion("productname is null");
            return (Criteria) this;
        }

        public Criteria andProductnameIsNotNull() {
            addCriterion("productname is not null");
            return (Criteria) this;
        }

        public Criteria andProductnameEqualTo(String value) {
            addCriterion("productname =", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotEqualTo(String value) {
            addCriterion("productname <>", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameGreaterThan(String value) {
            addCriterion("productname >", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameGreaterThanOrEqualTo(String value) {
            addCriterion("productname >=", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameLessThan(String value) {
            addCriterion("productname <", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameLessThanOrEqualTo(String value) {
            addCriterion("productname <=", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameLike(String value) {
            addCriterion("productname like", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotLike(String value) {
            addCriterion("productname not like", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameIn(List<String> values) {
            addCriterion("productname in", values, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotIn(List<String> values) {
            addCriterion("productname not in", values, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameBetween(String value1, String value2) {
            addCriterion("productname between", value1, value2, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotBetween(String value1, String value2) {
            addCriterion("productname not between", value1, value2, "productname");
            return (Criteria) this;
        }

        public Criteria andGgmodelIsNull() {
            addCriterion("ggmodel is null");
            return (Criteria) this;
        }

        public Criteria andGgmodelIsNotNull() {
            addCriterion("ggmodel is not null");
            return (Criteria) this;
        }

        public Criteria andGgmodelEqualTo(String value) {
            addCriterion("ggmodel =", value, "ggmodel");
            return (Criteria) this;
        }

        public Criteria andGgmodelNotEqualTo(String value) {
            addCriterion("ggmodel <>", value, "ggmodel");
            return (Criteria) this;
        }

        public Criteria andGgmodelGreaterThan(String value) {
            addCriterion("ggmodel >", value, "ggmodel");
            return (Criteria) this;
        }

        public Criteria andGgmodelGreaterThanOrEqualTo(String value) {
            addCriterion("ggmodel >=", value, "ggmodel");
            return (Criteria) this;
        }

        public Criteria andGgmodelLessThan(String value) {
            addCriterion("ggmodel <", value, "ggmodel");
            return (Criteria) this;
        }

        public Criteria andGgmodelLessThanOrEqualTo(String value) {
            addCriterion("ggmodel <=", value, "ggmodel");
            return (Criteria) this;
        }

        public Criteria andGgmodelLike(String value) {
            addCriterion("ggmodel like", value, "ggmodel");
            return (Criteria) this;
        }

        public Criteria andGgmodelNotLike(String value) {
            addCriterion("ggmodel not like", value, "ggmodel");
            return (Criteria) this;
        }

        public Criteria andGgmodelIn(List<String> values) {
            addCriterion("ggmodel in", values, "ggmodel");
            return (Criteria) this;
        }

        public Criteria andGgmodelNotIn(List<String> values) {
            addCriterion("ggmodel not in", values, "ggmodel");
            return (Criteria) this;
        }

        public Criteria andGgmodelBetween(String value1, String value2) {
            addCriterion("ggmodel between", value1, value2, "ggmodel");
            return (Criteria) this;
        }

        public Criteria andGgmodelNotBetween(String value1, String value2) {
            addCriterion("ggmodel not between", value1, value2, "ggmodel");
            return (Criteria) this;
        }

        public Criteria andRepUsernameIsNull() {
            addCriterion("rep_username is null");
            return (Criteria) this;
        }

        public Criteria andRepUsernameIsNotNull() {
            addCriterion("rep_username is not null");
            return (Criteria) this;
        }

        public Criteria andRepUsernameEqualTo(String value) {
            addCriterion("rep_username =", value, "repUsername");
            return (Criteria) this;
        }

        public Criteria andRepUsernameNotEqualTo(String value) {
            addCriterion("rep_username <>", value, "repUsername");
            return (Criteria) this;
        }

        public Criteria andRepUsernameGreaterThan(String value) {
            addCriterion("rep_username >", value, "repUsername");
            return (Criteria) this;
        }

        public Criteria andRepUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("rep_username >=", value, "repUsername");
            return (Criteria) this;
        }

        public Criteria andRepUsernameLessThan(String value) {
            addCriterion("rep_username <", value, "repUsername");
            return (Criteria) this;
        }

        public Criteria andRepUsernameLessThanOrEqualTo(String value) {
            addCriterion("rep_username <=", value, "repUsername");
            return (Criteria) this;
        }

        public Criteria andRepUsernameLike(String value) {
            addCriterion("rep_username like", value, "repUsername");
            return (Criteria) this;
        }

        public Criteria andRepUsernameNotLike(String value) {
            addCriterion("rep_username not like", value, "repUsername");
            return (Criteria) this;
        }

        public Criteria andRepUsernameIn(List<String> values) {
            addCriterion("rep_username in", values, "repUsername");
            return (Criteria) this;
        }

        public Criteria andRepUsernameNotIn(List<String> values) {
            addCriterion("rep_username not in", values, "repUsername");
            return (Criteria) this;
        }

        public Criteria andRepUsernameBetween(String value1, String value2) {
            addCriterion("rep_username between", value1, value2, "repUsername");
            return (Criteria) this;
        }

        public Criteria andRepUsernameNotBetween(String value1, String value2) {
            addCriterion("rep_username not between", value1, value2, "repUsername");
            return (Criteria) this;
        }

        public Criteria andRedescriptionIsNull() {
            addCriterion("redescription is null");
            return (Criteria) this;
        }

        public Criteria andRedescriptionIsNotNull() {
            addCriterion("redescription is not null");
            return (Criteria) this;
        }

        public Criteria andRedescriptionEqualTo(String value) {
            addCriterion("redescription =", value, "redescription");
            return (Criteria) this;
        }

        public Criteria andRedescriptionNotEqualTo(String value) {
            addCriterion("redescription <>", value, "redescription");
            return (Criteria) this;
        }

        public Criteria andRedescriptionGreaterThan(String value) {
            addCriterion("redescription >", value, "redescription");
            return (Criteria) this;
        }

        public Criteria andRedescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("redescription >=", value, "redescription");
            return (Criteria) this;
        }

        public Criteria andRedescriptionLessThan(String value) {
            addCriterion("redescription <", value, "redescription");
            return (Criteria) this;
        }

        public Criteria andRedescriptionLessThanOrEqualTo(String value) {
            addCriterion("redescription <=", value, "redescription");
            return (Criteria) this;
        }

        public Criteria andRedescriptionLike(String value) {
            addCriterion("redescription like", value, "redescription");
            return (Criteria) this;
        }

        public Criteria andRedescriptionNotLike(String value) {
            addCriterion("redescription not like", value, "redescription");
            return (Criteria) this;
        }

        public Criteria andRedescriptionIn(List<String> values) {
            addCriterion("redescription in", values, "redescription");
            return (Criteria) this;
        }

        public Criteria andRedescriptionNotIn(List<String> values) {
            addCriterion("redescription not in", values, "redescription");
            return (Criteria) this;
        }

        public Criteria andRedescriptionBetween(String value1, String value2) {
            addCriterion("redescription between", value1, value2, "redescription");
            return (Criteria) this;
        }

        public Criteria andRedescriptionNotBetween(String value1, String value2) {
            addCriterion("redescription not between", value1, value2, "redescription");
            return (Criteria) this;
        }

        public Criteria andRepNumIsNull() {
            addCriterion("rep_num is null");
            return (Criteria) this;
        }

        public Criteria andRepNumIsNotNull() {
            addCriterion("rep_num is not null");
            return (Criteria) this;
        }

        public Criteria andRepNumEqualTo(String value) {
            addCriterion("rep_num =", value, "repNum");
            return (Criteria) this;
        }

        public Criteria andRepNumNotEqualTo(String value) {
            addCriterion("rep_num <>", value, "repNum");
            return (Criteria) this;
        }

        public Criteria andRepNumGreaterThan(String value) {
            addCriterion("rep_num >", value, "repNum");
            return (Criteria) this;
        }

        public Criteria andRepNumGreaterThanOrEqualTo(String value) {
            addCriterion("rep_num >=", value, "repNum");
            return (Criteria) this;
        }

        public Criteria andRepNumLessThan(String value) {
            addCriterion("rep_num <", value, "repNum");
            return (Criteria) this;
        }

        public Criteria andRepNumLessThanOrEqualTo(String value) {
            addCriterion("rep_num <=", value, "repNum");
            return (Criteria) this;
        }

        public Criteria andRepNumLike(String value) {
            addCriterion("rep_num like", value, "repNum");
            return (Criteria) this;
        }

        public Criteria andRepNumNotLike(String value) {
            addCriterion("rep_num not like", value, "repNum");
            return (Criteria) this;
        }

        public Criteria andRepNumIn(List<String> values) {
            addCriterion("rep_num in", values, "repNum");
            return (Criteria) this;
        }

        public Criteria andRepNumNotIn(List<String> values) {
            addCriterion("rep_num not in", values, "repNum");
            return (Criteria) this;
        }

        public Criteria andRepNumBetween(String value1, String value2) {
            addCriterion("rep_num between", value1, value2, "repNum");
            return (Criteria) this;
        }

        public Criteria andRepNumNotBetween(String value1, String value2) {
            addCriterion("rep_num not between", value1, value2, "repNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chec_report
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}