package cn.junang.sys.model;

import java.util.Date;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.pid
     *
     * @mbg.generated
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.linkid
     *
     * @mbg.generated
     */
    private Long linkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.mgr_id
     *
     * @mbg.generated
     */
    private Long mgrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.isdel
     *
     * @mbg.generated
     */
    private Boolean isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.isstop
     *
     * @mbg.generated
     */
    private Boolean isstop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.optime
     *
     * @mbg.generated
     */
    private Date optime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.opid
     *
     * @mbg.generated
     */
    private Long opid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.id
     *
     * @return the value of tb_department.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.id
     *
     * @param id the value for tb_department.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.pid
     *
     * @return the value of tb_department.pid
     *
     * @mbg.generated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.pid
     *
     * @param pid the value for tb_department.pid
     *
     * @mbg.generated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.name
     *
     * @return the value of tb_department.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.name
     *
     * @param name the value for tb_department.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.tel
     *
     * @return the value of tb_department.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.tel
     *
     * @param tel the value for tb_department.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.phone
     *
     * @return the value of tb_department.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.phone
     *
     * @param phone the value for tb_department.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.linkid
     *
     * @return the value of tb_department.linkid
     *
     * @mbg.generated
     */
    public Long getLinkid() {
        return linkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.linkid
     *
     * @param linkid the value for tb_department.linkid
     *
     * @mbg.generated
     */
    public void setLinkid(Long linkid) {
        this.linkid = linkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.address
     *
     * @return the value of tb_department.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.address
     *
     * @param address the value for tb_department.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.mgr_id
     *
     * @return the value of tb_department.mgr_id
     *
     * @mbg.generated
     */
    public Long getMgrId() {
        return mgrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.mgr_id
     *
     * @param mgrId the value for tb_department.mgr_id
     *
     * @mbg.generated
     */
    public void setMgrId(Long mgrId) {
        this.mgrId = mgrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.isdel
     *
     * @return the value of tb_department.isdel
     *
     * @mbg.generated
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.isdel
     *
     * @param isdel the value for tb_department.isdel
     *
     * @mbg.generated
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.isstop
     *
     * @return the value of tb_department.isstop
     *
     * @mbg.generated
     */
    public Boolean getIsstop() {
        return isstop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.isstop
     *
     * @param isstop the value for tb_department.isstop
     *
     * @mbg.generated
     */
    public void setIsstop(Boolean isstop) {
        this.isstop = isstop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.remark
     *
     * @return the value of tb_department.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.remark
     *
     * @param remark the value for tb_department.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.ctime
     *
     * @return the value of tb_department.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.ctime
     *
     * @param ctime the value for tb_department.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.optime
     *
     * @return the value of tb_department.optime
     *
     * @mbg.generated
     */
    public Date getOptime() {
        return optime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.optime
     *
     * @param optime the value for tb_department.optime
     *
     * @mbg.generated
     */
    public void setOptime(Date optime) {
        this.optime = optime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.opid
     *
     * @return the value of tb_department.opid
     *
     * @mbg.generated
     */
    public Long getOpid() {
        return opid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.opid
     *
     * @param opid the value for tb_department.opid
     *
     * @mbg.generated
     */
    public void setOpid(Long opid) {
        this.opid = opid;
    }
}