package cn.junang.sys.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class Donation_formExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    public Donation_formExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDonNameIsNull() {
            addCriterion("don_name is null");
            return (Criteria) this;
        }

        public Criteria andDonNameIsNotNull() {
            addCriterion("don_name is not null");
            return (Criteria) this;
        }

        public Criteria andDonNameEqualTo(String value) {
            addCriterion("don_name =", value, "donName");
            return (Criteria) this;
        }

        public Criteria andDonNameNotEqualTo(String value) {
            addCriterion("don_name <>", value, "donName");
            return (Criteria) this;
        }

        public Criteria andDonNameGreaterThan(String value) {
            addCriterion("don_name >", value, "donName");
            return (Criteria) this;
        }

        public Criteria andDonNameGreaterThanOrEqualTo(String value) {
            addCriterion("don_name >=", value, "donName");
            return (Criteria) this;
        }

        public Criteria andDonNameLessThan(String value) {
            addCriterion("don_name <", value, "donName");
            return (Criteria) this;
        }

        public Criteria andDonNameLessThanOrEqualTo(String value) {
            addCriterion("don_name <=", value, "donName");
            return (Criteria) this;
        }

        public Criteria andDonNameLike(String value) {
            addCriterion("don_name like", value, "donName");
            return (Criteria) this;
        }

        public Criteria andDonNameNotLike(String value) {
            addCriterion("don_name not like", value, "donName");
            return (Criteria) this;
        }

        public Criteria andDonNameIn(List<String> values) {
            addCriterion("don_name in", values, "donName");
            return (Criteria) this;
        }

        public Criteria andDonNameNotIn(List<String> values) {
            addCriterion("don_name not in", values, "donName");
            return (Criteria) this;
        }

        public Criteria andDonNameBetween(String value1, String value2) {
            addCriterion("don_name between", value1, value2, "donName");
            return (Criteria) this;
        }

        public Criteria andDonNameNotBetween(String value1, String value2) {
            addCriterion("don_name not between", value1, value2, "donName");
            return (Criteria) this;
        }

        public Criteria andDonSuppliesIsNull() {
            addCriterion("don_supplies is null");
            return (Criteria) this;
        }

        public Criteria andDonSuppliesIsNotNull() {
            addCriterion("don_supplies is not null");
            return (Criteria) this;
        }

        public Criteria andDonSuppliesEqualTo(String value) {
            addCriterion("don_supplies =", value, "donSupplies");
            return (Criteria) this;
        }

        public Criteria andDonSuppliesNotEqualTo(String value) {
            addCriterion("don_supplies <>", value, "donSupplies");
            return (Criteria) this;
        }

        public Criteria andDonSuppliesGreaterThan(String value) {
            addCriterion("don_supplies >", value, "donSupplies");
            return (Criteria) this;
        }

        public Criteria andDonSuppliesGreaterThanOrEqualTo(String value) {
            addCriterion("don_supplies >=", value, "donSupplies");
            return (Criteria) this;
        }

        public Criteria andDonSuppliesLessThan(String value) {
            addCriterion("don_supplies <", value, "donSupplies");
            return (Criteria) this;
        }

        public Criteria andDonSuppliesLessThanOrEqualTo(String value) {
            addCriterion("don_supplies <=", value, "donSupplies");
            return (Criteria) this;
        }

        public Criteria andDonSuppliesLike(String value) {
            addCriterion("don_supplies like", value, "donSupplies");
            return (Criteria) this;
        }

        public Criteria andDonSuppliesNotLike(String value) {
            addCriterion("don_supplies not like", value, "donSupplies");
            return (Criteria) this;
        }

        public Criteria andDonSuppliesIn(List<String> values) {
            addCriterion("don_supplies in", values, "donSupplies");
            return (Criteria) this;
        }

        public Criteria andDonSuppliesNotIn(List<String> values) {
            addCriterion("don_supplies not in", values, "donSupplies");
            return (Criteria) this;
        }

        public Criteria andDonSuppliesBetween(String value1, String value2) {
            addCriterion("don_supplies between", value1, value2, "donSupplies");
            return (Criteria) this;
        }

        public Criteria andDonSuppliesNotBetween(String value1, String value2) {
            addCriterion("don_supplies not between", value1, value2, "donSupplies");
            return (Criteria) this;
        }

        public Criteria andClassificationIsNull() {
            addCriterion("classification is null");
            return (Criteria) this;
        }

        public Criteria andClassificationIsNotNull() {
            addCriterion("classification is not null");
            return (Criteria) this;
        }

        public Criteria andClassificationEqualTo(String value) {
            addCriterion("classification =", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationNotEqualTo(String value) {
            addCriterion("classification <>", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationGreaterThan(String value) {
            addCriterion("classification >", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationGreaterThanOrEqualTo(String value) {
            addCriterion("classification >=", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationLessThan(String value) {
            addCriterion("classification <", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationLessThanOrEqualTo(String value) {
            addCriterion("classification <=", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationLike(String value) {
            addCriterion("classification like", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationNotLike(String value) {
            addCriterion("classification not like", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationIn(List<String> values) {
            addCriterion("classification in", values, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationNotIn(List<String> values) {
            addCriterion("classification not in", values, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationBetween(String value1, String value2) {
            addCriterion("classification between", value1, value2, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationNotBetween(String value1, String value2) {
            addCriterion("classification not between", value1, value2, "classification");
            return (Criteria) this;
        }

        public Criteria andSpeModelIsNull() {
            addCriterion("spe_model is null");
            return (Criteria) this;
        }

        public Criteria andSpeModelIsNotNull() {
            addCriterion("spe_model is not null");
            return (Criteria) this;
        }

        public Criteria andSpeModelEqualTo(String value) {
            addCriterion("spe_model =", value, "speModel");
            return (Criteria) this;
        }

        public Criteria andSpeModelNotEqualTo(String value) {
            addCriterion("spe_model <>", value, "speModel");
            return (Criteria) this;
        }

        public Criteria andSpeModelGreaterThan(String value) {
            addCriterion("spe_model >", value, "speModel");
            return (Criteria) this;
        }

        public Criteria andSpeModelGreaterThanOrEqualTo(String value) {
            addCriterion("spe_model >=", value, "speModel");
            return (Criteria) this;
        }

        public Criteria andSpeModelLessThan(String value) {
            addCriterion("spe_model <", value, "speModel");
            return (Criteria) this;
        }

        public Criteria andSpeModelLessThanOrEqualTo(String value) {
            addCriterion("spe_model <=", value, "speModel");
            return (Criteria) this;
        }

        public Criteria andSpeModelLike(String value) {
            addCriterion("spe_model like", value, "speModel");
            return (Criteria) this;
        }

        public Criteria andSpeModelNotLike(String value) {
            addCriterion("spe_model not like", value, "speModel");
            return (Criteria) this;
        }

        public Criteria andSpeModelIn(List<String> values) {
            addCriterion("spe_model in", values, "speModel");
            return (Criteria) this;
        }

        public Criteria andSpeModelNotIn(List<String> values) {
            addCriterion("spe_model not in", values, "speModel");
            return (Criteria) this;
        }

        public Criteria andSpeModelBetween(String value1, String value2) {
            addCriterion("spe_model between", value1, value2, "speModel");
            return (Criteria) this;
        }

        public Criteria andSpeModelNotBetween(String value1, String value2) {
            addCriterion("spe_model not between", value1, value2, "speModel");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNull() {
            addCriterion("quantity is null");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNotNull() {
            addCriterion("quantity is not null");
            return (Criteria) this;
        }

        public Criteria andQuantityEqualTo(Integer value) {
            addCriterion("quantity =", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotEqualTo(Integer value) {
            addCriterion("quantity <>", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThan(Integer value) {
            addCriterion("quantity >", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("quantity >=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThan(Integer value) {
            addCriterion("quantity <", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("quantity <=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityIn(List<Integer> values) {
            addCriterion("quantity in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotIn(List<Integer> values) {
            addCriterion("quantity not in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityBetween(Integer value1, Integer value2) {
            addCriterion("quantity between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("quantity not between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andDonDataIsNull() {
            addCriterion("don_data is null");
            return (Criteria) this;
        }

        public Criteria andDonDataIsNotNull() {
            addCriterion("don_data is not null");
            return (Criteria) this;
        }

        public Criteria andDonDataEqualTo(Date value) {
            addCriterionForJDBCDate("don_data =", value, "donData");
            return (Criteria) this;
        }

        public Criteria andDonDataNotEqualTo(Date value) {
            addCriterionForJDBCDate("don_data <>", value, "donData");
            return (Criteria) this;
        }

        public Criteria andDonDataGreaterThan(Date value) {
            addCriterionForJDBCDate("don_data >", value, "donData");
            return (Criteria) this;
        }

        public Criteria andDonDataGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("don_data >=", value, "donData");
            return (Criteria) this;
        }

        public Criteria andDonDataLessThan(Date value) {
            addCriterionForJDBCDate("don_data <", value, "donData");
            return (Criteria) this;
        }

        public Criteria andDonDataLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("don_data <=", value, "donData");
            return (Criteria) this;
        }

        public Criteria andDonDataIn(List<Date> values) {
            addCriterionForJDBCDate("don_data in", values, "donData");
            return (Criteria) this;
        }

        public Criteria andDonDataNotIn(List<Date> values) {
            addCriterionForJDBCDate("don_data not in", values, "donData");
            return (Criteria) this;
        }

        public Criteria andDonDataBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("don_data between", value1, value2, "donData");
            return (Criteria) this;
        }

        public Criteria andDonDataNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("don_data not between", value1, value2, "donData");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table donation_form
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}