package cn.junang.sys.model;

import java.util.Date;

public class Pur_information {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_information.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_information.pur_number
     *
     * @mbg.generated
     */
    private String purNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_information.sup_name
     *
     * @mbg.generated
     */
    private String supName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_information.spe_model
     *
     * @mbg.generated
     */
    private String speModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_information.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_information.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_information.pur_content
     *
     * @mbg.generated
     */
    private String purContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_information.supplier
     *
     * @mbg.generated
     */
    private String supplier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_information.con_person
     *
     * @mbg.generated
     */
    private String conPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_information.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_information.data
     *
     * @mbg.generated
     */
    private Date data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_information.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_information.buyer
     *
     * @mbg.generated
     */
    private Integer buyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_information.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_information.classification
     *
     * @mbg.generated
     */
    private String classification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_information.inv_id
     *
     * @mbg.generated
     */
    private Integer invId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_information.buy_id
     *
     * @mbg.generated
     */
    private Integer buyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_information.sup_id
     *
     * @mbg.generated
     */
    private Integer supId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_information.id
     *
     * @return the value of pur_information.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_information.id
     *
     * @param id the value for pur_information.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_information.pur_number
     *
     * @return the value of pur_information.pur_number
     *
     * @mbg.generated
     */
    public String getPurNumber() {
        return purNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_information.pur_number
     *
     * @param purNumber the value for pur_information.pur_number
     *
     * @mbg.generated
     */
    public void setPurNumber(String purNumber) {
        this.purNumber = purNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_information.sup_name
     *
     * @return the value of pur_information.sup_name
     *
     * @mbg.generated
     */
    public String getSupName() {
        return supName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_information.sup_name
     *
     * @param supName the value for pur_information.sup_name
     *
     * @mbg.generated
     */
    public void setSupName(String supName) {
        this.supName = supName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_information.spe_model
     *
     * @return the value of pur_information.spe_model
     *
     * @mbg.generated
     */
    public String getSpeModel() {
        return speModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_information.spe_model
     *
     * @param speModel the value for pur_information.spe_model
     *
     * @mbg.generated
     */
    public void setSpeModel(String speModel) {
        this.speModel = speModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_information.unit
     *
     * @return the value of pur_information.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_information.unit
     *
     * @param unit the value for pur_information.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_information.quantity
     *
     * @return the value of pur_information.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_information.quantity
     *
     * @param quantity the value for pur_information.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_information.pur_content
     *
     * @return the value of pur_information.pur_content
     *
     * @mbg.generated
     */
    public String getPurContent() {
        return purContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_information.pur_content
     *
     * @param purContent the value for pur_information.pur_content
     *
     * @mbg.generated
     */
    public void setPurContent(String purContent) {
        this.purContent = purContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_information.supplier
     *
     * @return the value of pur_information.supplier
     *
     * @mbg.generated
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_information.supplier
     *
     * @param supplier the value for pur_information.supplier
     *
     * @mbg.generated
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_information.con_person
     *
     * @return the value of pur_information.con_person
     *
     * @mbg.generated
     */
    public String getConPerson() {
        return conPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_information.con_person
     *
     * @param conPerson the value for pur_information.con_person
     *
     * @mbg.generated
     */
    public void setConPerson(String conPerson) {
        this.conPerson = conPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_information.phone
     *
     * @return the value of pur_information.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_information.phone
     *
     * @param phone the value for pur_information.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_information.data
     *
     * @return the value of pur_information.data
     *
     * @mbg.generated
     */
    public Date getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_information.data
     *
     * @param data the value for pur_information.data
     *
     * @mbg.generated
     */
    public void setData(Date data) {
        this.data = data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_information.status
     *
     * @return the value of pur_information.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_information.status
     *
     * @param status the value for pur_information.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_information.buyer
     *
     * @return the value of pur_information.buyer
     *
     * @mbg.generated
     */
    public Integer getBuyer() {
        return buyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_information.buyer
     *
     * @param buyer the value for pur_information.buyer
     *
     * @mbg.generated
     */
    public void setBuyer(Integer buyer) {
        this.buyer = buyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_information.remarks
     *
     * @return the value of pur_information.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_information.remarks
     *
     * @param remarks the value for pur_information.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_information.classification
     *
     * @return the value of pur_information.classification
     *
     * @mbg.generated
     */
    public String getClassification() {
        return classification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_information.classification
     *
     * @param classification the value for pur_information.classification
     *
     * @mbg.generated
     */
    public void setClassification(String classification) {
        this.classification = classification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_information.inv_id
     *
     * @return the value of pur_information.inv_id
     *
     * @mbg.generated
     */
    public Integer getInvId() {
        return invId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_information.inv_id
     *
     * @param invId the value for pur_information.inv_id
     *
     * @mbg.generated
     */
    public void setInvId(Integer invId) {
        this.invId = invId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_information.buy_id
     *
     * @return the value of pur_information.buy_id
     *
     * @mbg.generated
     */
    public Integer getBuyId() {
        return buyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_information.buy_id
     *
     * @param buyId the value for pur_information.buy_id
     *
     * @mbg.generated
     */
    public void setBuyId(Integer buyId) {
        this.buyId = buyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_information.sup_id
     *
     * @return the value of pur_information.sup_id
     *
     * @mbg.generated
     */
    public Integer getSupId() {
        return supId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_information.sup_id
     *
     * @param supId the value for pur_information.sup_id
     *
     * @mbg.generated
     */
    public void setSupId(Integer supId) {
        this.supId = supId;
    }
}