package cn.junang.sys.model;

public class Receipt_from {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt_from.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt_from.job_number
     *
     * @mbg.generated
     */
    private String jobNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt_from.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt_from.dept
     *
     * @mbg.generated
     */
    private String dept;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt_from.id
     *
     * @return the value of receipt_from.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt_from.id
     *
     * @param id the value for receipt_from.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt_from.job_number
     *
     * @return the value of receipt_from.job_number
     *
     * @mbg.generated
     */
    public String getJobNumber() {
        return jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt_from.job_number
     *
     * @param jobNumber the value for receipt_from.job_number
     *
     * @mbg.generated
     */
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt_from.name
     *
     * @return the value of receipt_from.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt_from.name
     *
     * @param name the value for receipt_from.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt_from.dept
     *
     * @return the value of receipt_from.dept
     *
     * @mbg.generated
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt_from.dept
     *
     * @param dept the value for receipt_from.dept
     *
     * @mbg.generated
     */
    public void setDept(String dept) {
        this.dept = dept;
    }
}