package cn.junang.sys.model;

import java.util.Date;

public class StockOutinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_outinfo.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_outinfo.out_number
     *
     * @mbg.generated
     */
    private String outNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_outinfo.sup_name
     *
     * @mbg.generated
     */
    private String supName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_outinfo.out_quantity
     *
     * @mbg.generated
     */
    private Integer outQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_outinfo.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_outinfo.spe_model
     *
     * @mbg.generated
     */
    private String speModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_outinfo.out_address
     *
     * @mbg.generated
     */
    private String outAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_outinfo.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_outinfo.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_outinfo.id
     *
     * @return the value of stock_outinfo.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_outinfo.id
     *
     * @param id the value for stock_outinfo.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_outinfo.out_number
     *
     * @return the value of stock_outinfo.out_number
     *
     * @mbg.generated
     */
    public String getOutNumber() {
        return outNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_outinfo.out_number
     *
     * @param outNumber the value for stock_outinfo.out_number
     *
     * @mbg.generated
     */
    public void setOutNumber(String outNumber) {
        this.outNumber = outNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_outinfo.sup_name
     *
     * @return the value of stock_outinfo.sup_name
     *
     * @mbg.generated
     */
    public String getSupName() {
        return supName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_outinfo.sup_name
     *
     * @param supName the value for stock_outinfo.sup_name
     *
     * @mbg.generated
     */
    public void setSupName(String supName) {
        this.supName = supName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_outinfo.out_quantity
     *
     * @return the value of stock_outinfo.out_quantity
     *
     * @mbg.generated
     */
    public Integer getOutQuantity() {
        return outQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_outinfo.out_quantity
     *
     * @param outQuantity the value for stock_outinfo.out_quantity
     *
     * @mbg.generated
     */
    public void setOutQuantity(Integer outQuantity) {
        this.outQuantity = outQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_outinfo.unit
     *
     * @return the value of stock_outinfo.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_outinfo.unit
     *
     * @param unit the value for stock_outinfo.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_outinfo.spe_model
     *
     * @return the value of stock_outinfo.spe_model
     *
     * @mbg.generated
     */
    public String getSpeModel() {
        return speModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_outinfo.spe_model
     *
     * @param speModel the value for stock_outinfo.spe_model
     *
     * @mbg.generated
     */
    public void setSpeModel(String speModel) {
        this.speModel = speModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_outinfo.out_address
     *
     * @return the value of stock_outinfo.out_address
     *
     * @mbg.generated
     */
    public String getOutAddress() {
        return outAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_outinfo.out_address
     *
     * @param outAddress the value for stock_outinfo.out_address
     *
     * @mbg.generated
     */
    public void setOutAddress(String outAddress) {
        this.outAddress = outAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_outinfo.create_time
     *
     * @return the value of stock_outinfo.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_outinfo.create_time
     *
     * @param createTime the value for stock_outinfo.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_outinfo.remarks
     *
     * @return the value of stock_outinfo.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_outinfo.remarks
     *
     * @param remarks the value for stock_outinfo.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}