package cn.junang.sys.model;

import java.util.Date;

public class WareInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ware_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ware_info.war_number
     *
     * @mbg.generated
     */
    private String warNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ware_info.sup_name
     *
     * @mbg.generated
     */
    private String supName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ware_info.spe_model
     *
     * @mbg.generated
     */
    private String speModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ware_info.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ware_info.war_quantity
     *
     * @mbg.generated
     */
    private Integer warQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ware_info.war_type
     *
     * @mbg.generated
     */
    private String warType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ware_info.sup_source
     *
     * @mbg.generated
     */
    private String supSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ware_info.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ware_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ware_info.receiver
     *
     * @mbg.generated
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ware_info.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ware_info.id
     *
     * @return the value of ware_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ware_info.id
     *
     * @param id the value for ware_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ware_info.war_number
     *
     * @return the value of ware_info.war_number
     *
     * @mbg.generated
     */
    public String getWarNumber() {
        return warNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ware_info.war_number
     *
     * @param warNumber the value for ware_info.war_number
     *
     * @mbg.generated
     */
    public void setWarNumber(String warNumber) {
        this.warNumber = warNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ware_info.sup_name
     *
     * @return the value of ware_info.sup_name
     *
     * @mbg.generated
     */
    public String getSupName() {
        return supName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ware_info.sup_name
     *
     * @param supName the value for ware_info.sup_name
     *
     * @mbg.generated
     */
    public void setSupName(String supName) {
        this.supName = supName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ware_info.spe_model
     *
     * @return the value of ware_info.spe_model
     *
     * @mbg.generated
     */
    public String getSpeModel() {
        return speModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ware_info.spe_model
     *
     * @param speModel the value for ware_info.spe_model
     *
     * @mbg.generated
     */
    public void setSpeModel(String speModel) {
        this.speModel = speModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ware_info.unit
     *
     * @return the value of ware_info.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ware_info.unit
     *
     * @param unit the value for ware_info.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ware_info.war_quantity
     *
     * @return the value of ware_info.war_quantity
     *
     * @mbg.generated
     */
    public Integer getWarQuantity() {
        return warQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ware_info.war_quantity
     *
     * @param warQuantity the value for ware_info.war_quantity
     *
     * @mbg.generated
     */
    public void setWarQuantity(Integer warQuantity) {
        this.warQuantity = warQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ware_info.war_type
     *
     * @return the value of ware_info.war_type
     *
     * @mbg.generated
     */
    public String getWarType() {
        return warType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ware_info.war_type
     *
     * @param warType the value for ware_info.war_type
     *
     * @mbg.generated
     */
    public void setWarType(String warType) {
        this.warType = warType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ware_info.sup_source
     *
     * @return the value of ware_info.sup_source
     *
     * @mbg.generated
     */
    public String getSupSource() {
        return supSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ware_info.sup_source
     *
     * @param supSource the value for ware_info.sup_source
     *
     * @mbg.generated
     */
    public void setSupSource(String supSource) {
        this.supSource = supSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ware_info.sort
     *
     * @return the value of ware_info.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ware_info.sort
     *
     * @param sort the value for ware_info.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ware_info.create_time
     *
     * @return the value of ware_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ware_info.create_time
     *
     * @param createTime the value for ware_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ware_info.receiver
     *
     * @return the value of ware_info.receiver
     *
     * @mbg.generated
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ware_info.receiver
     *
     * @param receiver the value for ware_info.receiver
     *
     * @mbg.generated
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ware_info.remarks
     *
     * @return the value of ware_info.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ware_info.remarks
     *
     * @param remarks the value for ware_info.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}