package cn.junang.sys.mapper;

import cn.junang.sys.model.Biz_supplier;
import cn.junang.sys.model.Biz_supplierExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Biz_supplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_supplier
     *
     * @mbg.generated
     */
    long countByExample(Biz_supplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_supplier
     *
     * @mbg.generated
     */
    int deleteByExample(Biz_supplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_supplier
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_supplier
     *
     * @mbg.generated
     */
    int insert(Biz_supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_supplier
     *
     * @mbg.generated
     */
    int insertSelective(Biz_supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_supplier
     *
     * @mbg.generated
     */
    List<Biz_supplier> selectByExample(Biz_supplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_supplier
     *
     * @mbg.generated
     */
    Biz_supplier selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_supplier
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Biz_supplier record, @Param("example") Biz_supplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_supplier
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Biz_supplier record, @Param("example") Biz_supplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_supplier
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Biz_supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_supplier
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Biz_supplier record);
}