package cn.junang.sys.mapper;

import cn.junang.sys.model.Byuer;
import cn.junang.sys.model.ByuerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ByuerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table byuer
     *
     * @mbg.generated
     */
    long countByExample(ByuerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table byuer
     *
     * @mbg.generated
     */
    int deleteByExample(ByuerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table byuer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table byuer
     *
     * @mbg.generated
     */
    int insert(Byuer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table byuer
     *
     * @mbg.generated
     */
    int insertSelective(Byuer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table byuer
     *
     * @mbg.generated
     */
    List<Byuer> selectByExample(ByuerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table byuer
     *
     * @mbg.generated
     */
    Byuer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table byuer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Byuer record, @Param("example") ByuerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table byuer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Byuer record, @Param("example") ByuerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table byuer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Byuer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table byuer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Byuer record);
}