package cn.junang.sys.mapper;

import cn.junang.sys.model.Chec_plan;
import cn.junang.sys.model.Chec_planExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Chec_planMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_plan
     *
     * @mbg.generated
     */
    long countByExample(Chec_planExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_plan
     *
     * @mbg.generated
     */
    int deleteByExample(Chec_planExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_plan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_plan
     *
     * @mbg.generated
     */
    int insert(Chec_plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_plan
     *
     * @mbg.generated
     */
    int insertSelective(Chec_plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_plan
     *
     * @mbg.generated
     */
    List<Chec_plan> selectByExample(Chec_planExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_plan
     *
     * @mbg.generated
     */
    Chec_plan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_plan
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Chec_plan record, @Param("example") Chec_planExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_plan
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Chec_plan record, @Param("example") Chec_planExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Chec_plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Chec_plan record);
}