package cn.junang.sys.mapper;

import cn.junang.sys.model.Chec_report;
import cn.junang.sys.model.Chec_reportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Chec_reportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    long countByExample(Chec_reportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    int deleteByExample(Chec_reportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    int insert(Chec_report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    int insertSelective(Chec_report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    List<Chec_report> selectByExample(Chec_reportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    Chec_report selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Chec_report record, @Param("example") Chec_reportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Chec_report record, @Param("example") Chec_reportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Chec_report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Chec_report record);
}