package cn.junang.sys.mapper;

import cn.junang.sys.model.Chec_manage;
import cn.junang.sys.model.Chec_manageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Chec_manageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_manage
     *
     * @mbg.generated
     */
    long countByExample(Chec_manageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_manage
     *
     * @mbg.generated
     */
    int deleteByExample(Chec_manageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_manage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_manage
     *
     * @mbg.generated
     */
    int insert(Chec_manage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_manage
     *
     * @mbg.generated
     */
    int insertSelective(Chec_manage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_manage
     *
     * @mbg.generated
     */
    List<Chec_manage> selectByExample(Chec_manageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_manage
     *
     * @mbg.generated
     */
    Chec_manage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_manage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Chec_manage record, @Param("example") Chec_manageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_manage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Chec_manage record, @Param("example") Chec_manageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_manage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Chec_manage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chec_manage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Chec_manage record);
}