package cn.junang.sys.mapper;

import cn.junang.sys.model.Donation_form;
import cn.junang.sys.model.Donation_formExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Donation_formMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    long countByExample(Donation_formExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    int deleteByExample(Donation_formExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    int insert(Donation_form record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    int insertSelective(Donation_form record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    List<Donation_form> selectByExample(Donation_formExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    Donation_form selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Donation_form record, @Param("example") Donation_formExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Donation_form record, @Param("example") Donation_formExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Donation_form record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table donation_form
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Donation_form record);
}