package cn.junang.sys.mapper;

import cn.junang.sys.model.Inventory_info;
import cn.junang.sys.model.Inventory_infoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Inventory_infoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_info
     *
     * @mbg.generated
     */
    long countByExample(Inventory_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_info
     *
     * @mbg.generated
     */
    int deleteByExample(Inventory_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_info
     *
     * @mbg.generated
     */
    int insert(Inventory_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_info
     *
     * @mbg.generated
     */
    int insertSelective(Inventory_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_info
     *
     * @mbg.generated
     */
    List<Inventory_info> selectByExample(Inventory_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_info
     *
     * @mbg.generated
     */
    Inventory_info selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Inventory_info record, @Param("example") Inventory_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Inventory_info record, @Param("example") Inventory_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Inventory_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Inventory_info record);
}