package cn.junang.sys.mapper;

import cn.junang.sys.model.Matecategory;
import cn.junang.sys.model.MatecategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MatecategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    long countByExample(MatecategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    int deleteByExample(MatecategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    int insert(Matecategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    int insertSelective(Matecategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    List<Matecategory> selectByExample(MatecategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    Matecategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Matecategory record, @Param("example") MatecategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Matecategory record, @Param("example") MatecategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Matecategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Matecategory record);
}