package cn.junang.sys.mapper;

import cn.junang.sys.model.Mate_category;
import cn.junang.sys.model.Mate_categoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Mate_categoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    long countByExample(Mate_categoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    int deleteByExample(Mate_categoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    int insert(Mate_category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    int insertSelective(Mate_category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    List<Mate_category> selectByExample(Mate_categoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    Mate_category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Mate_category record, @Param("example") Mate_categoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Mate_category record, @Param("example") Mate_categoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Mate_category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mate_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Mate_category record);
}