package cn.junang.sys.mapper;

import cn.junang.sys.model.Pur_application;
import cn.junang.sys.model.Pur_applicationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Pur_applicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_application
     *
     * @mbg.generated
     */
    long countByExample(Pur_applicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_application
     *
     * @mbg.generated
     */
    int deleteByExample(Pur_applicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_application
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_application
     *
     * @mbg.generated
     */
    int insert(Pur_application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_application
     *
     * @mbg.generated
     */
    int insertSelective(Pur_application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_application
     *
     * @mbg.generated
     */
    List<Pur_application> selectByExample(Pur_applicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_application
     *
     * @mbg.generated
     */
    Pur_application selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_application
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Pur_application record, @Param("example") Pur_applicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_application
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Pur_application record, @Param("example") Pur_applicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_application
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Pur_application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_application
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Pur_application record);
}