package cn.junang.sys.mapper;

import cn.junang.sys.model.Pur_information;
import cn.junang.sys.model.Pur_informationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Pur_informationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_information
     *
     * @mbg.generated
     */
    long countByExample(Pur_informationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_information
     *
     * @mbg.generated
     */
    int deleteByExample(Pur_informationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_information
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_information
     *
     * @mbg.generated
     */
    int insert(Pur_information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_information
     *
     * @mbg.generated
     */
    int insertSelective(Pur_information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_information
     *
     * @mbg.generated
     */
    List<Pur_information> selectByExample(Pur_informationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_information
     *
     * @mbg.generated
     */
    Pur_information selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_information
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Pur_information record, @Param("example") Pur_informationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_information
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Pur_information record, @Param("example") Pur_informationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_information
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Pur_information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pur_information
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Pur_information record);
}