package cn.junang.sys.mapper;

import cn.junang.sys.model.Receipt_from;
import cn.junang.sys.model.Receipt_fromExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Receipt_fromMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_from
     *
     * @mbg.generated
     */
    long countByExample(Receipt_fromExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_from
     *
     * @mbg.generated
     */
    int deleteByExample(Receipt_fromExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_from
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_from
     *
     * @mbg.generated
     */
    int insert(Receipt_from record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_from
     *
     * @mbg.generated
     */
    int insertSelective(Receipt_from record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_from
     *
     * @mbg.generated
     */
    List<Receipt_from> selectByExample(Receipt_fromExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_from
     *
     * @mbg.generated
     */
    Receipt_from selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_from
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Receipt_from record, @Param("example") Receipt_fromExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_from
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Receipt_from record, @Param("example") Receipt_fromExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_from
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Receipt_from record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_from
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Receipt_from record);
}