package cn.junang.sys.mapper;

import cn.junang.sys.model.Scrap_from;
import cn.junang.sys.model.Scrap_fromExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Scrap_fromMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap_from
     *
     * @mbg.generated
     */
    long countByExample(Scrap_fromExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap_from
     *
     * @mbg.generated
     */
    int deleteByExample(Scrap_fromExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap_from
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap_from
     *
     * @mbg.generated
     */
    int insert(Scrap_from record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap_from
     *
     * @mbg.generated
     */
    int insertSelective(Scrap_from record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap_from
     *
     * @mbg.generated
     */
    List<Scrap_from> selectByExample(Scrap_fromExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap_from
     *
     * @mbg.generated
     */
    Scrap_from selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap_from
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Scrap_from record, @Param("example") Scrap_fromExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap_from
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Scrap_from record, @Param("example") Scrap_fromExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap_from
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Scrap_from record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap_from
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Scrap_from record);
}