package cn.junang.sys.mapper;

import cn.junang.sys.model.StockOutinfo;
import cn.junang.sys.model.StockOutinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockOutinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    long countByExample(StockOutinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    int deleteByExample(StockOutinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    int insert(StockOutinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    int insertSelective(StockOutinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    List<StockOutinfo> selectByExample(StockOutinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    StockOutinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StockOutinfo record, @Param("example") StockOutinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StockOutinfo record, @Param("example") StockOutinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StockOutinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StockOutinfo record);
}