package cn.junang.sys.mapper;

import cn.junang.sys.model.Stock_outinfo;
import cn.junang.sys.model.Stock_outinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Stock_outinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    long countByExample(Stock_outinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    int deleteByExample(Stock_outinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    int insert(Stock_outinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    int insertSelective(Stock_outinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    List<Stock_outinfo> selectByExample(Stock_outinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    Stock_outinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Stock_outinfo record, @Param("example") Stock_outinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Stock_outinfo record, @Param("example") Stock_outinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Stock_outinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_outinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Stock_outinfo record);
}