package cn.junang.sys.mapper;

import cn.junang.sys.model.WareInfo;
import cn.junang.sys.model.WareInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WareInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware_info
     *
     * @mbg.generated
     */
    long countByExample(WareInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware_info
     *
     * @mbg.generated
     */
    int deleteByExample(WareInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware_info
     *
     * @mbg.generated
     */
    int insert(WareInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware_info
     *
     * @mbg.generated
     */
    int insertSelective(WareInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware_info
     *
     * @mbg.generated
     */
    List<WareInfo> selectByExample(WareInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware_info
     *
     * @mbg.generated
     */
    WareInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WareInfo record, @Param("example") WareInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WareInfo record, @Param("example") WareInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WareInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ware_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WareInfo record);
}